version: '2'

services:
  influxdb:
    image: influxdb:1.2.4
    container_name: influxdb
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    environment:
          - "INFLUXDB_REPORTING_DISABLED=true"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      #- /srv/docker/influxdb/data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      #- ./data/influxdb:/var/lib/influxdb
    restart: always

  telegraf:
    image: telegraf:1.6
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf_jolokia.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/provisioning/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    links:
      - influxdb
    restart: always
